FROM alpine:3.19

RUN apk update && \
    apk add --no-cache mariadb mariadb-client bash

RUN mkdir -p /var/lib/mysql /var/run/mysqld \
    && chown -R mysql:mysql /var/lib/mysql /var/run/mysqld

COPY ./tools/server.cnf /etc/my.cnf.d/mariadb-server.cnf

COPY ./tools/script.sh ./script.sh

RUN chmod +x script.sh

EXPOSE 3306

CMD ["/script.sh"]