FROM alpine:3.22

RUN apk update && \
    apk add --no-cache nginx openssl && \
    rm -rf /var/cache/apk/*

RUN mkdir -p /etc/nginx/ssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/nginx/ssl/aghergho.42.fr.key \
    -out /etc/nginx/ssl/aghergho.42.fr.crt \
    -subj "/C=MA/ST=DRAATAFILAT/L=errachidia/O=1337/CN=localhost/emailAddress=test@example.com"

COPY ./tools/nginx.conf /etc/nginx/nginx.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]